[workspace]
members = [
]

[package]
name = "curso-basico"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.7.1"
csv = "1.1.6"
